#!/bin/bash

function cleanup() {
  rm boundary_token.txt
  pushd compose
  docker-compose rm -fs 
  popd
  pushd terraform/
  rm terraform.tfstate*
  popd
  exit 0
}
trap cleanup SIGKILL SIGINT

function init_compose() {
  pushd compose/
  docker-compose up -d
  popd
}

function init_terraform() {
  pushd terraform
  ./terraform init
  ./terraform apply -auto-approve
  popd
}

if [ "$1" ==  "all" ]; then
  init_compose
  init_terraform
elif [ "$1" ==  "cleanup" ]; then
  cleanup
elif [ "$1" ==  "login" ]; then
  boundary authenticate password -auth-method-id="$2" -login-name=lorris -password=password -keyring-type=none -format=json | jq -r ".token" > boundary_token.txt 
  #export BOUNDARY_TOKEN=$(cat boundary_token.txt)
elif [ "$1" ==  "test_redis" ]; then
  boundary connect -exec redis-cli -target-id "$2"
else
  echo "cmd not found: try 'all', 'login', or 'cleanup'"
fi