#!/bin/bash

function cleanup() {
  rm boundary_token.txt
  pushd compose
  docker-compose rm -fs 
  popd
  pushd terraform/
  rm terraform.tfstate*
  popd
  exit 0
}
trap cleanup SIGKILL SIGINT

function init_compose() {
  pushd compose/
  docker-compose up -d
  popd
}

function init_terraform() {
  pushd terraform
  ./terraform init
  ./terraform apply -auto-approve
  popd
}

if [ "$1" ==  "all" ]; then
  init_compose
  init_terraform
elif [ "$1" ==  "cleanup" ]; then
  cleanup
elif [ "$1" ==  "login" ]; then
  boundary authenticate password -auth-method-id="$2" -login-name="$3" -password="$4" -keyring-type=none -format=json | jq -r ".token" > boundary_token.txt 
elif [ "$1" ==  "connect" ]; then
  boundary connect -exec "$2" -target-id "$3" -token $(cat boundary_token.txt) -- -p {{boundary.port}}
else
  echo "cmd not found: try 'all', 'login', or 'cleanup'"
fi