version: "3.1"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=boundary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#init database
  db-init:
    image: hashicorp/boundary:0.1.1
    container_name: boundary_db_init
    command: ["database", "init", "-config", "/boundary/boundary.hcl"]
    volumes:
      - "${PWD}/:/boundary/"
    environment:
      - BOUNDARY_PG_URL=postgresql://postgres:postgres@db/boundary?sslmode=disable
    depends_on:
      - db
#start boundary server
  boundary:
    image: hashicorp/boundary:0.1.1
    container_name: boundary_server
    command: ["server", "-config", "/boundary/boundary.hcl"]
    volumes:
      - "${PWD}/:/boundary/"
    ports:
      - "9200:9200"
      - "9201:9201"
      - "9202:9202"
    environment:
      - BOUNDARY_PG_URL=postgresql://postgres:postgres@db/boundary?sslmode=disable
    depends_on:
      - db-init

# Private Database Targets - not exposed to host network, only available via Boundary
  mysql:
    image: mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=password'
#exposition de redis en attendant le fix de l'issue
  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"

  # cassandra:
  #   image: bitnami/cassandra:latest
  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
  #   environment:
  #     - 'ACCEPT_EULA=Y'
  #     - 'SA_PASSWORD=yourStrong(!)Password'